In [1]:
import numpy as np

## Copy VS view

### 1. copy create anpoter array changes not made in original array
### 2. The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [7]:
# Copy Example
arr = np.array([4,5,6,7,8,9])
arr1 = arr.copy()
arr1[4] = 120
print(arr)
print(arr1)

[4 5 6 7 8 9]
[  4   5   6   7 120   9]


In [12]:
# view Example
arr  = np.array([5,6,7,8,9])
arr1 = arr.view()
arr1[3] = 50
print(arr)
print(arr1)

[ 5  6  7 50  9]
[ 5  6  7 50  9]
None
[ 5  6  7 50  9]


## check weather array have their own data

In [13]:
print(arr.base)
print(arr1.base)

None
[ 5  6  7 50  9]


## Shape VS Reshape
### shape that returns a tuple with each index having the number of corresponding elements.
#### Reshaping means changing the shape of an array.

#### The shape of an array is the number of elements in each dimension.

#### By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [16]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [29]:
arr = np.array([1,2,3,4,5,6,7,89,8])
print(arr.ndim)
x = arr.reshape(3, 3)
print(x.ndim)

1
2


In [30]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 89,  8]])

Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [44]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = arr.reshape(2, 2, -1)
y

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [45]:
y.ndim

3

### Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

In [46]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
z = arr.reshape(-1)
z

array([1, 2, 3, 4, 5, 6, 7, 8])