## import package and array creation

In [21]:
import numpy as np

In [5]:
# creating 1-Darray
arr = np.array([1,2,3,4,5])
type(arr)
arr1= np.array((1,2,3,4,5,6))
type(arr1)

numpy.ndarray

## Accessing 1D array

In [25]:
arr1= np.array((1,2,3,4,5,6))
print(arr1[2])

3


In [9]:
# Creating 0-D array
arr = np.array(43)
arr
type(arr)

numpy.ndarray

In [10]:
#creating 2-D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


## Acessing 2-d array

In [30]:
arr[0, 1]

array([4, 5, 6])

In [44]:
# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]])

print(arr.ndim)

3


## acessing 3D array

In [49]:
arr[0, 2, 2]


9

In [16]:
# Check how many dimensions the arrays have:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [20]:
# Create an array with 5 dimensions and verify that it has 5 dimensions:
a = np.array([1,2,3,4,5,6,7], ndmin=5)
print(a.ndim)
print(a)

5
[[[[[1 2 3 4 5 6 7]]]]]


In [53]:
a[0, 0, 0, 0, 6]

7